### ISSUE TITLE
topo speedup

### ISSUE THREAD

**Issue by jimrojerTNO** [Nieuwe-Warmte-Nu/rtc-tools-heat-network#24]

**Comment by Tklauw-TNO** [comment]
I've done a thorough review of the code and made sure all changes that were on CI are incorporated here. Only file that I did not migrate contained functions that are now integrated in the tests/utils_tests.py file. These functions where named slightly differently on CI and in a different file, but in their old name they probably caused some trouble since they were were auto-discovered by the Pytest, I guess?

Running GROW on my own laptop both the goals with prio 1 and with prio 2 take just over 30 seconds respectively to solve. The result was a very close match to the results obtained for the same file with the old implementation (up to commit ae5771b).

Up next are tests to ensure the introduced variables and constraints work :).
